name: VoidWarp
version: ${project.version}
main: org.lushplugins.voidwarp.VoidWarp
api-version: 1.16
description: Teleports you to a specific location, runs a command or warps you to the nearest warp when you go above or below a specified Y level.
softdepend:
  - Essentials
  - EssentialsSpawn
  - HuskHomes
  - PlaceholderAPI
  - SunLight
  - WarpSystem
  - WorldGuard
commands:
  vwreload:
    description: Reloads the plugin
    usage: /vwreload
permissions:
  voidwarp.admin.reload:
    description: Allows you to reload the VoidWarp plugin
    default: op
  voidwarp.admin.bypass:
    description: Bypass the VoidWarp regions
    default: false
